import { supabase } from "../supabase/client.js";
import { ORG_ID, buildStoreFromRows } from "./mappers.js";

const orgFilter = (q) => q.eq("org_id", ORG_ID);

export async function loadStoreFromSupabase() {
  if (!supabase) throw new Error("Supabase is not configured. Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY.");

  const [
    settingsRes,
    departmentsRes,
    shiftsRes,
    deptShiftsRes,
    leaveTypesRes,
    profilesRes,
    profileDeptsRes,
    salariesRes,
    ecsRes,
    attendanceRes,
    leavesRes,
    correctionsRes,
    offDaysRes,
    holidaysRes,
    advanceReqRes,
    advanceInstRes,
    advanceAppRes,
    advanceAuditRes,
    salaryHistRes,
    salarySchedRes,
    notificationsRes,
    alertsRes,
    announcementsRes,
    auditRes,
    auditArchRes,
    entAuditRes,
    loginRes,
    pwdResetsRes,
    histReqRes,
    officesRes,
    punchesRes,
    payrollRes,
    payslipsRes,
  ] = await Promise.all([
    supabase.from("org_settings").select("settings").eq("org_id", ORG_ID).maybeSingle(),
    orgFilter(supabase.from("departments").select("*")),
    orgFilter(supabase.from("shifts").select("*")),
    orgFilter(supabase.from("department_shifts").select("*")),
    orgFilter(supabase.from("leave_types").select("*")),
    orgFilter(supabase.from("profiles").select("*")),
    orgFilter(supabase.from("profile_departments").select("*")),
    supabase.from("user_salaries").select("*"),
    orgFilter(supabase.from("user_emergency_contacts").select("*")),
    orgFilter(supabase.from("attendance").select("*")),
    orgFilter(supabase.from("leaves").select("*")),
    orgFilter(supabase.from("corrections").select("*")),
    orgFilter(supabase.from("off_days").select("*")),
    orgFilter(supabase.from("resolved_holidays").select("holiday_date")),
    orgFilter(supabase.from("advance_salary_requests").select("*")),
    orgFilter(supabase.from("advance_installments").select("*")),
    orgFilter(supabase.from("advance_approvals").select("*")),
    orgFilter(supabase.from("advance_audit_logs").select("*")),
    orgFilter(supabase.from("salary_history").select("*")),
    orgFilter(supabase.from("salary_schedules").select("*")),
    orgFilter(supabase.from("notifications").select("*")),
    orgFilter(supabase.from("alerts").select("*")),
    orgFilter(supabase.from("announcements").select("*")),
    orgFilter(supabase.from("audit_log").select("*")),
    orgFilter(supabase.from("audit_archive").select("*")),
    orgFilter(supabase.from("enterprise_audit_logs").select("*")),
    orgFilter(supabase.from("login_activity").select("*")),
    orgFilter(supabase.from("password_resets").select("*")),
    orgFilter(supabase.from("history_requests").select("*")),
    orgFilter(supabase.from("office_locations").select("*")),
    orgFilter(supabase.from("location_punches").select("*")),
    orgFilter(supabase.from("payroll_runs").select("*")),
    orgFilter(supabase.from("payslips").select("*")),
  ]);

  const firstErr =
    settingsRes.error ||
    departmentsRes.error ||
    profilesRes.error;
  if (firstErr) throw firstErr;

  return buildStoreFromRows({
    settings: settingsRes.data,
    departments: departmentsRes.data || [],
    shifts: shiftsRes.data || [],
    departmentShifts: deptShiftsRes.data || [],
    leaveTypes: leaveTypesRes.data || [],
    profiles: profilesRes.data || [],
    profileDepartments: profileDeptsRes.data || [],
    salaries: salariesRes.data || [],
    emergencyContacts: ecsRes.data || [],
    attendance: attendanceRes.data || [],
    leaves: leavesRes.data || [],
    corrections: correctionsRes.data || [],
    offDays: offDaysRes.data || [],
    resolvedHolidays: holidaysRes.data || [],
    advanceRequests: advanceReqRes.data || [],
    advanceInstallments: advanceInstRes.data || [],
    advanceApprovals: advanceAppRes.data || [],
    advanceAuditLogs: advanceAuditRes.data || [],
    salaryHistory: salaryHistRes.data || [],
    salarySchedules: salarySchedRes.data || [],
    notifications: notificationsRes.data || [],
    alerts: alertsRes.data || [],
    announcements: announcementsRes.data || [],
    auditLog: auditRes.data || [],
    auditArchive: auditArchRes.data || [],
    enterpriseAuditLogs: entAuditRes.data || [],
    loginActivity: loginRes.data || [],
    passwordResets: pwdResetsRes.data || [],
    historyRequests: histReqRes.data || [],
    officeLocations: officesRes.data || [],
    locationPunches: punchesRes.data || [],
    payrollRuns: payrollRes.data || [],
    payslips: payslipsRes.data || [],
  });
}
